export default {
  "login": "arman1211",
  "id": 57310610,
  "node_id": "MDQ6VXNlcjU3MzEwNjEw",
  "avatar_url": "https://avatars.githubusercontent.com/u/57310610?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/arman1211",
  "html_url": "https://github.com/arman1211",
  "followers_url": "https://api.github.com/users/arman1211/followers",
  "following_url": "https://api.github.com/users/arman1211/following{/other_user}",
  "gists_url": "https://api.github.com/users/arman1211/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/arman1211/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/arman1211/subscriptions",
  "organizations_url": "https://api.github.com/users/arman1211/orgs",
  "repos_url": "https://api.github.com/users/arman1211/repos",
  "events_url": "https://api.github.com/users/arman1211/events{/privacy}",
  "received_events_url": "https://api.github.com/users/arman1211/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mohammad Sharfuddin",
  "company": "Own business",
  "blog": "",
  "location": "Chattagram",
  "email": null,
  "hireable": null,
  "bio": "Passionate MERN Stack developer",
  "twitter_username": "Arman50886673",
  "public_repos": 24,
  "public_gists": 0,
  "followers": 2,
  "following": 2,
  "created_at": "2019-11-03T06:14:45Z",
  "updated_at": "2023-02-26T15:48:29Z"
};