export default [
  {
    "login": "nahid10git",
    "id": 87413035,
    "node_id": "MDQ6VXNlcjg3NDEzMDM1",
    "avatar_url": "https://avatars.githubusercontent.com/u/87413035?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nahid10git",
    "html_url": "https://github.com/nahid10git",
    "followers_url": "https://api.github.com/users/nahid10git/followers",
    "following_url": "https://api.github.com/users/nahid10git/following{/other_user}",
    "gists_url": "https://api.github.com/users/nahid10git/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nahid10git/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nahid10git/subscriptions",
    "organizations_url": "https://api.github.com/users/nahid10git/orgs",
    "repos_url": "https://api.github.com/users/nahid10git/repos",
    "events_url": "https://api.github.com/users/nahid10git/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nahid10git/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "promitchy",
    "id": 100062966,
    "node_id": "U_kgDOBfbW9g",
    "avatar_url": "https://avatars.githubusercontent.com/u/100062966?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/promitchy",
    "html_url": "https://github.com/promitchy",
    "followers_url": "https://api.github.com/users/promitchy/followers",
    "following_url": "https://api.github.com/users/promitchy/following{/other_user}",
    "gists_url": "https://api.github.com/users/promitchy/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/promitchy/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/promitchy/subscriptions",
    "organizations_url": "https://api.github.com/users/promitchy/orgs",
    "repos_url": "https://api.github.com/users/promitchy/repos",
    "events_url": "https://api.github.com/users/promitchy/events{/privacy}",
    "received_events_url": "https://api.github.com/users/promitchy/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "JCSIVO",
    "id": 104387283,
    "node_id": "U_kgDOBjjS0w",
    "avatar_url": "https://avatars.githubusercontent.com/u/104387283?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/JCSIVO",
    "html_url": "https://github.com/JCSIVO",
    "followers_url": "https://api.github.com/users/JCSIVO/followers",
    "following_url": "https://api.github.com/users/JCSIVO/following{/other_user}",
    "gists_url": "https://api.github.com/users/JCSIVO/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/JCSIVO/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/JCSIVO/subscriptions",
    "organizations_url": "https://api.github.com/users/JCSIVO/orgs",
    "repos_url": "https://api.github.com/users/JCSIVO/repos",
    "events_url": "https://api.github.com/users/JCSIVO/events{/privacy}",
    "received_events_url": "https://api.github.com/users/JCSIVO/received_events",
    "type": "User",
    "site_admin": false
  }
]